<a href="https://colab.research.google.com/github/sky309/Advertisement-Sale-prediction-from-an-existing-customer/blob/main/Ads__Sales_Prediction_for_Existing_Customers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sale Prediction from Existing customer - Logistic Regression

* <b>Dataset is consits of Customer age, Customer Salary and his response whether he buy the item or not.</b>

    Features:

    Age: Age of Customer

    Salary: Customer Salary in Thousands of Rs.

    Response: 0: Don't Buy, 1- Buy

* <b>Importing Libraries:</b>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

* <b> Loading the data: </b>

In [2]:
from google.colab import files
uploaded= files.upload()

Saving DigitalAd_dataset.csv to DigitalAd_dataset.csv


* <b> Summarizing Data:</b>

In [3]:
dataset= pd.read_csv("DigitalAd_dataset.csv")

In [4]:
print(dataset.shape)

(400, 3)


In [5]:
dataset.head()

Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1

* <b> Defining dependent and independent features: </b>

In [6]:
# Independent Features:
X= dataset.iloc[:,:-1].values

In [7]:
# Dependent Feature:
y= dataset.iloc[:,-1].values
y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

# <b> Splitting the dataset: </b>

In [8]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=0)

# <b>Feature Scaling:</b>

* Scaling is done to make all the features contribute equally to the result.
* Fit_Transform - fit method is calculating the mean and variance of each of the features present in our dataset.
* Transform - Transform method is transforming all the features using the respective mean and variance, here combne mean is calculate for all the features. 
* Just to give surprise to the model only using transform with test dataset.

In [9]:
# Scaling the dataset:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [10]:
# Logisric Regression Model instantiaon:
lr= LogisticRegression(random_state=0)

In [11]:
# fitting the model:
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
# Taking input for new customer:
age= int(input("Enter the Customer age"))
salary= int(input("Enter the salary of Customer"))
new_cust= [[age, salary]]

# Making prediction for new customer:
result= lr.predict(scaler.transform(new_cust))
print(result)
if result==1:
  print("Customer will buy")
else:
  print("Customer will not buy")

Enter the Customer age20
Enter the salary of Customer30000
[0]
Customer will not buy


In [13]:
# Predicted value of y for testing dataset.
y_pred= lr.predict(X_test)

In [14]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


In [15]:
# Creating instances for accuracy matrix and confusion matrx:
cm= confusion_matrix(y_test, y_pred)
ac= accuracy_score(y_test, y_pred)

In [16]:
# Model efficiency checking:
print("Confusion Matrix is:\n", cm)
print(f"accuracy of the model is:\n{ac*100}% ")

Confusion Matrix is:
 [[61  0]
 [20 19]]
accuracy of the model is:
80.0% 


<b>Conclusion:</b>

* I simply put the Logistic Regression Model.
* Accuracy can be increased by changing random_state value , changing   training dataset % or hyperparameter tuning.

<I><font color='red'>Thanks with lots of love</font><I>

                                          By
                                       Sarvesh
               https://www.linkedin.com/in/sarvesh-kumar-yadav-00a30a94/
                            https://www.instagram.com/skyt321/



                               Stay connected & updated






